### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jduepmeier** [Indidev/vocable-o#1]
Wenn man eine Sprache editiert ohne Wörter bekommt man ein "index out of range".

```
panic: runtime error: index out of range
goroutine 1 [running]: 
   main.edtVocables()      vocable-o.go:244 +0x785
   main.edtLang()            vocable-o.go:183 +0x1c4
   main.edtLangMenu()    vocable-o.go:156 +0x24b
   main.mainMenu()         vocable-o.go:50 +0xde
   main.main()                  vocable-o.go:31 +0xa4

goroutine 5 [syscall]:
   os/signal.loop()            /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
            created by os/signal.init·1
                                       /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [select]:
      github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
          termbox-go/api.go:321 +0x63f
             github.com/indidev/vocable-o/console.run()
             github.com/indidev/vocable-o/console/console.go:48 +0xcc
      created by github.com/indidev/vocable-o/console.Init
             github.com/indidev/vocable-o/console/console.go:31 +0x29

goroutine 7 [select]:
     github.com/nsf/termbox-go.func·001()
     github.com/nsf/termbox-go/api.go:87 +0x43bfirm, d - Delete
          created by github.com/nsf/termbox-go.Init
     github.com/nsf/termbox-go/api.go:106 +0x96a
```

**Comment by Indidev** [comment]
Danke, habs gefixt, menüs geben jetzt immer eine escape sequenz (-1) zurück wenn keine items vorhanden sind, aber enter gedrückt wird (gleicht dem drücken der esc taste).
